---
title: "06-codingquiz"
author: "Milo Coolman"
format: 
  html:
    embed-resources: true
---

# Question 1
```{r}
library(tidyverse)
path <- "https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/"
field_df <- read_csv(paste0(path, "field_study.csv"))
field_df

field_df_q1 <- field_df |> pivot_longer(cols = c(bio, psych, stats, cs), names_to = "field", values_to = "salary") |>
  group_by(year, field) |>
  summarise(med_salary = median(salary))

ggplot(data = field_df_q1, aes(x = year, y = med_salary)) +
  geom_line(aes(colour = field)) +
  scale_x_continuous(breaks = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019)) +
  scale_colour_viridis_d() +
  theme_minimal()
```

# Question 2
```{r}
field2019_df <- read_csv(paste0(path, "field_study2.csv"))
field2019_df

field2019_df_q2 <- field2019_df |> separate(col = variable, into = c("year", "variable2"), sep = 4) |>
  separate(col = variable2, into = c("field", "salary"), sep = "___") |>
  mutate(salary = parse_number(salary)) |> group_by(field) |> 
  summarise(mean_salary = mean(salary))
field2019_df_q2

ggplot(data = field2019_df_q2, aes(x = field, y = mean_salary)) +
  geom_col(aes(colour = field, fill = field)) +
  scale_colour_viridis_d() +
  scale_fill_viridis_d() +
  theme_minimal()
```

# Question 3
```{r}
late_df <- read_csv(paste0(path, "late.csv"))

late_df_q3 <- late_df |> mutate(late_or_not = if_else(late_or_not == "not late",
                                        true = "0",
                                        false = "1")) |>
  mutate(late_or_not = as.double(late_or_not)) |>
  group_by(student_id, semester) |>
  summarise(total_late = sum(late_or_not))
late_df_q3
```

# Question 4
This is not a reprex because it will not run without giving someone the file 'stat113.csv'. To make it a reprex, you would have to construct a tibble with maybe 3 or so rows of this dataset manually using a tibble.
```{r}
library(tidyverse)
library(here)
stat113 <- read_csv(here("data/stat113.csv"))
stat113
```

# Question 5
```{r}
library(tidyverse)
toy_df_quiz <- tibble(xvar = c("90", "83", "102", "50", "60", "90", "20", "40"),
                      other_info = c(4, 3, 2, 1, 5, 3, 2, 9))
toy_df_quiz <- toy_df_quiz |> mutate(xvar = as.double(xvar))

ggplot(data = toy_df_quiz, aes(x = xvar)) +
  geom_histogram() +
  scale_x_continuous(breaks = c(20, 40, 50, 60, 83, 90, 102))
```



