---
title: "10-dataimport"
author: "Milo Coolman"
format:
  html:
    embed-resources: true
---

# 10.1
```{r}
library(tidyverse)
library(here)
cars_df <- read_csv(here("data/mtcarsex.csv"))
head(cars_df)

cars_df <- read_csv(here("data/mtcarsex.csv"), skip = 2)
cars_df
```

```{r}
cars_df <- read_csv(here("data/mtcarsex.csv"), na = c("NA", "-999"), skip = 2)
head(cars_df)

read_csv(here("data/mtcarsex.csv"), na = c("NA", "-999"), skip = 2) |>
  spec()

cars_df <- read_csv(here("data/mtcarsex.csv"), na = c("NA", "-999"), skip = 2,
  col_types = cols(
  mpg = col_double(),
  cyl = col_factor(),
  disp = col_double(),
  hp = col_double(),
  drat = col_double(),
  wt = col_double(),
  qsec = col_double(),
  vs = col_factor(),
  am = col_double(),
  gear = col_double(),
  carb = col_double()
)) |>
  slice(-(1:2))
head(cars_df)
```

```{r}
oscars_df <- read_tsv(here("data/oscars.tsv"))
head(oscars_df)
```

```{r}
test_df <- read_csv(here("data/parsedf.csv"))
head(test_df)

test_df |> mutate(x2 = parse_number(x))
```

### Exercise 1
```{r}
fitness_df <- read_csv(here::here("data/higham_fitness_notclean.csv"),
  col_types = cols(
    Start = col_date(),
    active_cals = col_double(),
    distance = col_double(),
    flights = col_double(),
    steps = col_double(),
    month = col_factor(),
    weekday = col_factor(),
    dayofyear = col_double(),
    stepgoal = col_logical()))
fitness_df
```

# 10.2
```{r}
library(tidyverse)
library(rvest)

## provide the URL and name it something (in this case, url).
url <- "https://en.wikipedia.org/wiki/Gun_violence_in_the_United_States_by_state"

## read_html() convert the html code from the URL into something R can read
tab <- read_html(url) |> 
  html_nodes("table") ## html_nodes can grab only the tables 

test1 <- tab[[1]] |> html_table()
test1
test2 <- tab[[2]] |> html_table()
test2
test3 <- tab[[3]] |> html_table()
test3
```

```{r}
url <- "https://saintsathletics.com/sports/baseball/stats/2023"

tab <- read_html(url) |> html_nodes("table")
tab
obj <- tab[[1]] |> html_table()
obj
obj2 <- tab[[2]] |> html_table()
obj2
```

### Exercise 2
```{r}
url <- "https://www.stlawu.edu/offices/institutional-research/student-diversity-2021"
e2 <- read_html(url) |> html_nodes("table")
e2
exercise2 <- e2[[1]] |> html_table()
exercise2
```

# Class Exercises

### Class Exercise 1
```{r}
library(tidyverse)
df <- read_delim(here("data/birthdays.txt"), delim = " - ", 
                 skip = 4, 
                 col_names = c("date", "name", "species", "time"),
                 trim_ws = TRUE,
                 na = c("?", "N/A", "", "NA"),
                 col_types = "ccfc") |>
  mutate(time = parse_number(time))
head(df)
```

### Class Exercise 4
```{r}
library(rvest)
url1 <- "https://en.wikipedia.org/wiki/Josh_Allen_(quarterback)"
tab_allen_stats <- read_html(url1) |> html_nodes("table")
allen_df <- tab_allen_stats[[6]] |> html_table()
allen_df
## The issue ^^ is that the table on wikipedia has 2 rows of headers, creating
## some duplicate column names.

allen_stats <- tab_allen_stats[[6]] |> html_table(header = FALSE) 
## Puts both headers as rows in the dataframe
allen_stats

newnames <- paste(allen_stats[1, ], allen_stats[2, ])
## pasting names from both header rows together
allen_stats |> set_names(newnames) |>
  slice(-1, -2)
```

# Your Turn

### Your Turn 1
```{r}
url2 <- "https://saintsathletics.com/sports/mens-soccer/stats"
tab_slusoccer <- read_html(url2) |> html_nodes("table")
slu_soccer_df <- tab_slusoccer[[1]] |> html_table()
slu_soccer_df |> slice(2:8, 10, 11, 13:17) |>
  separate(col = Statistic, into = c("Statistic", "temp"), sep = "\r\n") |>
  select(1, 3, 4) |>
  rename(St.Lawrence = 'St. Lawrence',
         Opponents = 'Opponents\r\n                            OPP')
```



